name: tag
on:
  push:
    tags:
      - "*"
jobs:
  build-tag-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build tag image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ehco1996/django-sspanel
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
          dockerfile: Dockerfile.code
